[package]
name = "anemulator2"
version = "0.1.0"
edition = "2021"
authors = ["Matthias Finke <webmaster@pottgames.de>"]

[dependencies]
pixels = "0.6.0"
sdl2 = { version = "0.34.5", features = ["bundled", "raw-window-handle", "static-link"] }